export type { ArticleSearchOptions, Article, ArticleResult, ArticleGetOptions, PreprintFunder, PreprintVersionInfo, PreprintCorrespondingAuthor, PreprintDetails, PreprintPublishedVersion } from './types.js';
export { articleSearch, parseDateRange } from './search/index.js';
export { articleGet } from './detail/index.js';
export { deduplicateAndRank } from './search/dedup.js';
export { parseArticleId, isPreprintDoi } from './detail/id-resolution.js';
export { transformEuropePMC } from './search/europepmc.js';
export { transformSemanticScholar } from './search/semantic-scholar.js';
export { transformPubTator } from './search/pubtator.js';
export { transformLitSense } from './search/litsense.js';
export { transformPreprint } from './search/preprint.js';
export { getPreprintArticle, splitSemicolonAuthors } from './detail/preprint.js';
export { parsePubMedXml } from './transform/pubmed.js';
export { parseArxivAtomXml } from './transform/arxiv.js';
export { searchArxiv } from './search/arxiv.js';
export { parseOaXml } from './detail/open-access.js';
export { getCitations, clearCitationCache } from './citation/index.js';
export type { ArticleId, CitationRecord, CitationCount, SourceCitationResult, FederatedCitationResult } from './citation/types.js';
